### ISSUE TITLE
For some reason it can't loaded correctly

### ISSUE THREAD

**Issue by Jinphire** [PssbleTrngle/SliceAndDice#10]
### What happened?

When I tried to load the game, it crashed and gave me the message:
Create Slice & Dice (sliceanddice) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

### Mod Version

1.0.2

### Forge Version

40.1.76

### Relevant log output

```shell
I think it's easier this way: https://pastebin.com/LxZVCepN
```

**Comment by PssbleTrngle** [comment]
Have you added [kotlinforforge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)?

**Comment by Jinphire** [comment]
Hi, excuse me for the absence. No, I don't have Kotling

**Comment by Jinphire** [comment]
I leave the entire list of mods than I use:

Crafting automat 1.2.3
CC:C Bridge 1.1.0
Sophisticated Storage 0.4.8.93
Just Enough Items 9.7.1.232
The Graveyard 1.9.2
Goblin Traders 1.7.2
Sophisticated Core 0.4.11.89
Rubidium 0.5.3a
Industrialized Create 1.0.0
waystones 10.1.0
Forge Endertech 9.0.4.0
Advanced Finders 7.0.0.0
Comforts 5.0.0.4
Nature's compass 1.9.7
Serene Seasons 0.0NONE
Dave's Building Extended 4.8.1
Configured 1.5.3
Alcocraft 1.0.0
Sophisticated Backpacks 3.1.8.16.671
Guard Villagers 1.4.3
Bonsai Trees 3 3.1.0
Just Enough Effect Descriptio9n 1.11
Balm 3.1.0+0
Water Strainer 13.0.0
Wall-Jump! 1.3.7
Just Enough Resources 0.14.1.171
Rubidium Extras v1.3.2
Forge 40.1.76
Create Cafe 1.9.3
EggCrate 1.0.0
Conquest's Medieval Arms 1.0
Chipped 1.2.1
The Graveyard Biomes 1.1
Deepslate Generator 1.1.0
Terra Blender 1.1.0.102
Biomes O' Plenty 0.0NONE
Jade 5.2.3
Nekoration 1.7.5
Eyes in the Darkness 1.2.7
Easy Villagers 1.0.10
Pipez 1.1.5
Flywhell 0.6.5
Curios API 5.0.7.1
Patchouli 71.1
Xaero's Minimap 22.11.1
Oculus 1.2.5a
Collective 4.50
Ore Excavation 1.10.162
Double Slabs 5.0.0
libnonyumous 2.1.0
Apple Skin 2.4.0
Alex-s Delight 1.2.3
Citadel 1.11.3
Alex's Mobs 1.18.6
Farmer's Delight 1.1.2
Cultural Delights 0.11
Honey expansion 1.1.1
brewin' and Chewin' 1.0.1
Farmer's Respite 1.3.0
connected Glass 1.1.4
CC: Tweaked 1.100.9
Macaw's Furniture 3.0.1
Extended Flywheels 1.2.1
Create 0.5.0d
Create Deco 1.2.10
Some Assembly Required 2.0.8
Large Meals 0.2
Mob Catcher 1.1.3
Infinite Trading 2.0
Valhelsia Core 0.3.1
Valhelsia Structures 0.1.0
Dynamic Trees 0.11.0-Alpha2
Dynamic Trees for Biomes o' Plenty 3.0.0-ALPHA1
GeckoLib 3.0.36
Neko's enchanted Books 1.7.0

**Comment by PssbleTrngle** [comment]
Ah, that's the problem, this mod requires "kotlin for forge"
