### ISSUE TITLE
I can't craft slime with dough

### ISSUE THREAD

**Issue by ZharTX** [PssbleTrngle/SliceAndDice#101]
### What happened?

The dough item icon on JEI changes to a barrier icon and says empty tag, because of that I can't craft slime using dough.

### Loader

forge

### Mod Version

3.1.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
can you send me the `latest.log`?

**Comment by ZharTX** [comment]
[latest.log](https://github.com/PssbleTrngle/SliceAndDice/files/12310653/latest.log)

**Comment by PssbleTrngle** [comment]
Ok, the dough issue is caused because I have farmer's delight wheat dough as an required entry and you don't have that mod installed. I should probably change that to an optional entry, but are you sure  you do not want farmers delight? This mod is mainly there  to create compat for it

**Comment by PssbleTrngle** [comment]
There is also another issue with the `forge:tools/axes` tag in the log, I am not quite sure which mod causes this, but that also sound pretty bad

**Comment by ZharTX** [comment]
Ok, thank you very much for the response, I didn't use farm delight because it was written as optional and I didn't know much about the mod so I chose to be gradual. tysm
