### ISSUE TITLE
Incompatible with latest create fabric 1.19.2

### ISSUE THREAD

**Issue by sisby-folk** [PssbleTrngle/SliceAndDice#107]
### What happened?

`ClassNotFoundException: com.simibubi.create.content.AllSections`

with `sliceanddice-fabric-2.1.3-fabric.jar ` and `\create-fabric-0.5.1-c-build.1160+mc1.19.2.jar`

### Loader

fabric

### Mod Version

2.1.3

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
You should update your version of slice & dice
