### ISSUE TITLE
Unable to put anything in slicer

### ISSUE THREAD

**Issue by Grmmi** [PssbleTrngle/SliceAndDice#111]
### What happened?

I cant put anything in the slicer no matter how hard I try. Ive seen in previous post about tha log.latest file so here is mine. 
[latest.log](https://github.com/PssbleTrngle/SliceAndDice/files/12571820/latest.log)
I would enjoy the help a ton!

### Loader

forge

### Mod Version

1.1.3

### Minecraft Version

1.18

**Comment by PssbleTrngle** [comment]
is there a specific reason, why you are not using the latest version of this mod? I don't think this will solve it but it could be

**Comment by Grmmi** [comment]
Yeah Im just using a modpack, Ill try a newer version real quick

**Comment by Grmmi** [comment]
Also many of the newer versions need create 5.1.a and I cant seem to get that to work, or any later version either

**Comment by Grmmi** [comment]
After an hour of troubleshooting I havent been able to get anything other than 1.1.3 to work with both Create and its other addon mods.

**Comment by PssbleTrngle** [comment]
I am still not sure what this was caused by in the older version or if this is still an issue, do you know which create addons do not yet support the newest version?

**Comment by Grmmi** [comment]
If I change my create version it asks me to download a mod that doesn't exist. Create 5.1 is completely broken ATM and the mod I'm playing is completely built around that version of create. It would require an update of all 100 mods and some of them might not have the updates required. (By that version I mean whatever version the modpacks is using, not 5.1)
