### ISSUE TITLE
Incompatible Version

### ISSUE THREAD

**Issue by SaltSouls** [PssbleTrngle/SliceAndDice#112]
### What happened?

It would seem the version in the `mods.toml` file was set improperly. Current version of Create is '0.5.1.d'. There is no 'e' release as of yet.

### Loader

forge

### Mod Version

3.2.0

### Minecraft Version

1.20

### Relevant log output

```Shell
net.minecraftforge.fml.ModLoadingException: Mod §esliceanddice§r requires §6create§r §o0.5.1.e or above§r
```

**Comment by PssbleTrngle** [comment]
yes, there is [0.5.1.e](https://www.curseforge.com/minecraft/mc-mods/create/files/4762216). The only thing the latest slice & dice release does, is fix an error with the latest version, if you're not already using `0.5.1.e`, you can also downgrade slice & dice by one version

**Comment by SaltSouls** [comment]
Sorry, I was using modrinth and they hadn't updated it there.
