### ISSUE TITLE
Sprinkler is not craftable

### ISSUE THREAD

**Issue by Mudkip99** [PssbleTrngle/SliceAndDice#113]
### What happened?

I am unable to craft the sprinkler, not sure what's causing this issue. The recipe appears in JEI and the item appears in the creative menu, but it's impossible to craft in the inventory or a crafting table. 

### Loader

fabric

### Mod Version

3.0.0

### Minecraft Version

1.20

**Comment by Jacoomis** [comment]
Seems like its trying to use the forge version of pipes to craft.

**Comment by PssbleTrngle** [comment]
what do you mean with "forge version"?

**Comment by mikubean** [comment]
Ya need to swap out "tag": "c:plates/copper" with "tag": "c:copper_plates" in sprinkler.json. Its located in the recipes folder, for those not willing to wait for an update, you can open the jar with 7zip and go from there.
