### ISSUE TITLE
Kotlin Requirement

### ISSUE THREAD

**Issue by Ganon-Main** [PssbleTrngle/SliceAndDice#114]
### What happened?

When booting up the game, I get this message:
"Mod sliceanddice requires kotlinforforge _3 or above_; currently, kotlinforforge is _**not installed**_"

meanwhile, my mod folder:
![kotlinforgewtf](https://github.com/PssbleTrngle/SliceAndDice/assets/147432860/a35e36b7-233e-4c0d-a431-5dce3241b3c0)
 
I've tried downloading mutiple different versions of kotlin. In fact, I've been using this custom modpack for a long time with kotlinforforge 3.8.0, which has worked with no issues until attempting to play with this mod.

Is there a specific version of kotlin I need to be using or am I just making a silly mistake somewhere?

### Loader

forge

### Mod Version

1.3.2

### Minecraft Version

1.18

### Relevant log output

```Shell
[09Oct2023 12:31:41.171] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'kotlinforforge', Requested by: 'sliceanddice', Expected range: '[3,)', Actual version: '[MISSING]'
```

**Comment by PssbleTrngle** [comment]
Seems like kotlin for forge `3.4.0` or `3.8.0` does not register itself as a mod, which I think it did not always do.
Upgrading to the latest version of kotlin for forge should definitely solve the issue though

**Comment by Ganon-Main** [comment]
Seemed to work just fine. I used the most recent version compatible for 1.18.2 and it did the trick, good spotting. Good mod now that I can use it 👍

**Comment by PssbleTrngle** [comment]
Ok very nice and thank you very much 😁
