### ISSUE TITLE
sprinkler tick crash

### ISSUE THREAD

**Issue by netcore10** [PssbleTrngle/SliceAndDice#115]
### What happened?

when a block under it was broken it crashed the game

### Loader

fabric

### Mod Version

3.0.0

### Minecraft Version

1.20

### Relevant log output

```Shell
https://mclo.gs/JVD4CbX
```

**Comment by PssbleTrngle** [comment]
which create fabric version are you using?

**Comment by netcore10** [comment]
1.20.1 DM EARTH to fix sodium

**Comment by netcore10** [comment]
I found it'd built on v0.5.1.d but I guess some add ons don't work with it because they patched an issue create haven't yet. Maybe due to portinglib?

**Comment by PssbleTrngle** [comment]
sorry I'm a bit confused, where did you get that create file from?

**Comment by netcore10** [comment]
https://modrinth.com/mod/create-fabric-dme-edition

**Comment by PssbleTrngle** [comment]
oh ok, I'm not sure if I can support this fork at the same time, as the original mod itself. It's also written in their description, that addons will probably break when used in combination with it

**Comment by netcore10** [comment]
Fair enough, that's a shame, since sodium is broken on the latest create.
