### ISSUE TITLE
Unable to add knives or axes to the slicer

### ISSUE THREAD

**Issue by txukiakari** [PssbleTrngle/SliceAndDice#116]
### What happened?

I'm unable to add axes or knives to the slicer.

I'm currently playing on my own modpack with a lot of mods, and at some point I started to be unable to add the tools to the slicer. It was likely one of the many food mods, but I'm not sure how to narrow it down...

Here's a google sheet link to a spreadsheet with all of the mods: [Link](https://docs.google.com/spreadsheets/d/179qa97d9MgQLknWK1iPUp397kerOWf-j_JBpjduY0aA/edit?usp=sharing)

And here's a link to the client modpack if it'll help: [Link](https://www.dropbox.com/scl/fi/tnyyxv2apsea8x8m9kz30/modpack.zip?rlkey=860cdcn9wc4sacx0sz6wbndoz&dl=0)

[latest.log](https://github.com/PssbleTrngle/SliceAndDice/files/13225309/latest.log)

Thank you!

### Loader

forge

### Mod Version

1.3.2

### Minecraft Version

1.18

**Comment by PssbleTrngle** [comment]
Hi, this is a known issue (#92) and caused  by Twilight-Delight, which is not working properly but seems to not be updated anymore

**Comment by txukiakari** [comment]
Oh, I saw that issue but didn't read closely enough I guess. Thanks for the quick response! Removing Twilight's Delight fixed it.
