### ISSUE TITLE
Allow liquid fertilizer to waterlog blocks

### ISSUE THREAD

**Issue by CaptainPepperjack** [PssbleTrngle/SliceAndDice#12]
### Describe the feature you have in mind.

Allowing Liquid Fertilizer to waterlog blocks such as stairs/fences/slabs. 

### Does this solve a particular problem?

It would be just a nice small detail. I find the texture quite nice and allowing it to waterlog blocks increases its potential for aesthetic industrial agriculture building.

**Comment by PssbleTrngle** [comment]
This would be an incredible effort, as the entire minecraft codebase is coded in a way which only allows water to be used when waterlogging blocks. 
Nice suggestion but sadly way out of scope
