### ISSUE TITLE
Harvester capable of gathering Straw

### ISSUE THREAD

**Issue by TeslaReloaded** [PssbleTrngle/SliceAndDice#120]
### Describe the feature you have in mind.

Hello. I'd really like to ask for a version of Harvester that's capable of collecting not only the basic resource, but also Straw, like when a player is manually harvesting wheat with a knife, but automated version.

### Does this solve a particular problem?

Love the mod. Thank you!

**Comment by PssbleTrngle** [comment]
Tbh it feels like the normal harvester should already do that, maybe I'll just mixin into it to change its harvesting behavior to act like it's holding a knife
