### ISSUE TITLE
Cherry Wood and Slicer compatibility

### ISSUE THREAD

**Issue by opee2012** [PssbleTrngle/SliceAndDice#121]
### What happened?

With the axe in the slicer, cherry wood doesn't process into stripped logs and tree bark. Not sure if this is an issue for this mod or Farmer's Delight.

### Loader

fabric

### Mod Version

3.2.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Is there an equivalent farmers delight cutting recipe?

**Comment by opee2012** [comment]
The cutting recipe for cherry logs was actually just added yesterday. Good timing I guess ![Screenshot_20231209-082125~2.png](https://github.com/PssbleTrngle/SliceAndDice/assets/47112091/9f9cb418-c5d6-4df2-87a3-c55dab17362a)
