### ISSUE TITLE
Incompatible enchantments found on gear in loot chests

### ISSUE THREAD

**Issue by myriantics** [PssbleTrngle/SliceAndDice#123]
### What happened?

I opened some bastion chests, and was recieving crossbows with Sweeping Edge III and swords with Luck of the Sea II. After doing some troubleshooting, this mod surfaced as the root cause of the problem.

### Loader

fabric

### Mod Version

3.0.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
This mod does not do the slightest things with loot or enchantments, I have no idea how it could possibly be responsible for this

**Comment by myriantics** [comment]
Nevermind, testing was flawed, sorry to bother. Probably should have gotten more sleep before bug testing. happy new year!

**Comment by PssbleTrngle** [comment]
No problem, hope you found the culprit and happy new year to you too ☺️
