### ISSUE TITLE
Shears don't work on the slicer

### ISSUE THREAD

**Issue by WitherTM** [PssbleTrngle/SliceAndDice#124]
### What happened?

The shears item from vanilla minecraft does not work with the slicer block.
What I expected: the shears would be accepted by the Slicer and it will operate. 

### Loader

forge

### Mod Version

3.2.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
You have add it to the item tag as defined in the README

**Comment by WitherTM** [comment]
why is it not in the main mod? Farmer's Delight also has cutting recipes with shears

**Comment by WitherTM** [comment]
> You have add it to the item tag as defined in the README

tried this, doesn't seem to work?

**Comment by PssbleTrngle** [comment]
can you upload the datapack you created that does not work & the content of the `latest.log` file?

**Comment by WitherTM** [comment]
oh no sorry I should've closed this the thing in the README works

**Comment by AlanTheJaguar** [comment]
this bug is back the datapack doesnt work nor the editing of the allowed tools list
