### ISSUE TITLE
Liquid Fertilizer Ponder page shows Sprinkler's

### ISSUE THREAD

**Issue by Eggmanplant** [PssbleTrngle/SliceAndDice#125]
### What happened?

![Screenshot from 2024-01-01 14-03-59](https://github.com/PssbleTrngle/SliceAndDice/assets/126160675/6d598812-6209-4632-b334-25b38649c5cc)

### Loader

forge

### Mod Version

3.2.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
This is intended
