### ISSUE TITLE
Feature Request: Sprinklers extinguish fire

### ISSUE THREAD

**Issue by CaptainPepperjack** [PssbleTrngle/SliceAndDice#13]
### Describe the feature you have in mind.

Water Sprinklers extinguish fires below them and solidify lava source blocks into obsidian.

### Does this solve a particular problem?

I believe this would allow for some interesting mechanics in contraption designs.

**Comment by PssbleTrngle** [comment]
Sprinkler's with water right now act exactly as if it was raining below them.
I think that means they should be extinguishing fire (maybe not instantly), if not that is a bug.
Solidifying lava is too much I think, after all, it's just some sprinkles of water
