### ISSUE TITLE
Unable to add any tool to the Slicer

### ISSUE THREAD

**Issue by Boigotbooped** [PssbleTrngle/SliceAndDice#130]
### What happened?

I am aware there is another issue open on this sort of thing already but its been a bit and I have a different set of mods so I figured it may be worth bringing it to attention. I have tried everything I can think of to troubleshoot/fix the issue myself but have had no luck thus far. Sorry if this was an unnecessary post.

I believe this is the latest.log you'd need to look at any potential issue there
[latest.log](https://github.com/PssbleTrngle/SliceAndDice/files/14372559/latest.log)

### Loader

forge

### Mod Version

1.3.2

### Minecraft Version

1.18

**Comment by Boigotbooped** [comment]
I finally got it to work, seems that something about Twilight Delight and Farmer's Compat's tag systems were missing key tags that were messing with this, I might recommend prefacing these incompatibilities on the mod page if possible?

**Comment by PssbleTrngle** [comment]
Yeah the problem is that twilight delight is broken but no longer maintained for a while now, I've also opened an [issue](https://github.com/Laokuai233/Twilight-Delight/issues/26) on the repo
