### ISSUE TITLE
Create 1.20.1 v0.5.1.f incompatability

### ISSUE THREAD

**Issue by Hippopipo** [PssbleTrngle/SliceAndDice#133]
### What happened?

Crash with Create v0.5.1.f installed.

### Loader

fabric

### Mod Version

3.2.0

### Minecraft Version

1.20

### Relevant log output

```Shell
Crash report: https://mclo.gs/kjZZJmA
Latest.log: https://mclo.gs/WG90EJe
```

**Comment by Sunconure11** [comment]
Can confirm the same issue on 1.19.2

**Comment by pauliesnug** [comment]
+1 I have the same issue on 1.20.1

**Comment by NolanHewitt** [comment]
Can confirm on 1.20.1 fabric as well

**Comment by cai-tan** [comment]
confirmed same issue 1.20.1 fabric, with the `java.lang.NoSuchFieldError: MAIN_TAB` exception

**Comment by pauliesnug** [comment]
@PssbleTrngle it seems like this project isnt maintained

**Comment by PssbleTrngle** [comment]
@pauliesnug this issue has only been open for 2 days, this project is, like most mods for most modders a hobby and this is not a 24/7 hotline

**Comment by cai-tan** [comment]
Create 0.5.1f literally just released on Fabric four days ago (which I myself didn't know until just now to be completely honest) so reduce the temperature of your thrusters, friend

**Comment by pauliesnug** [comment]
> @pauliesnug this issue has only been open for 2 days, this project is, like most mods for most modders a hobby and this is not a 24/7 hotline

Hi, my apologies, I thought this was unmaintained because there hasnt been a commit/activity from you on this repo for a few months. thank you, no rush

**Comment by Sunconure11** [comment]
@PssbleTrngle Noticed you made the build for 1.19.2 on the repo. How long will that take to get to Modrinth?

**Comment by PssbleTrngle** [comment]
The version fixing this should be out now, happy downloading

**Comment by Sunconure11** [comment]
@PssbleTrngle Sorry to bug you about this, but while it seems you created a 1.19.2 build of this fix, you never released it. You may want to look into releasing it, if it is finished.

**Comment by PssbleTrngle** [comment]
Oh sorry, I did not know the previous 1.19.2 version was also crashing with create 0.5.1f, I thought that worked out of the box for me without changing everything but I'll look at it again

**Comment by PssbleTrngle** [comment]
@Sunconure11 I just tested it and the current version of slice & dice does already work with 0.5.1.f out of the box, is it crashing for you?

**Comment by Sunconure11** [comment]
I'll have to test the new 1.19.2 build once more Create addons update, since something changed with rendering
