### ISSUE TITLE
Slicer not accepting knives

### ISSUE THREAD

**Issue by SwiftAsTheWind** [PssbleTrngle/SliceAndDice#134]
### What happened?

Unable to insert any knives into the slicer

### Loader

forge

### Mod Version

1.3.2

### Minecraft Version

1.18

**Comment by PssbleTrngle** [comment]
I'm gonna need your log output, probably another mod causing the `forge:tools/knives` but to break

**Comment by SwiftAsTheWind** [comment]
Where could I find a log output? The bug is in-game and doesn't cause a crash. I will admit that I am using it in a custom personal modpack, so how could I help to source this issue?

**Comment by PssbleTrngle** [comment]
The log can be found under `logs/latest.log`

**Comment by SwiftAsTheWind** [comment]
Here is the log from my last playthrough:

[latest.log](https://github.com/PssbleTrngle/SliceAndDice/files/14629183/latest.log)

**Comment by PssbleTrngle** [comment]
Sorry, I think the that log cut off because you were playing for a long time, could you sent my a new one where you just start the game and open a join a world?

**Comment by PssbleTrngle** [comment]
And I see that you are playing with Twilight Forest, do you also happen to have Twilight Delight installed?

**Comment by SwiftAsTheWind** [comment]
Here is the immediate log after login:
[latest.log](https://github.com/PssbleTrngle/SliceAndDice/files/14643925/latest.log)

Also, yes Twilight Delight is also installed.

**Comment by SwiftAsTheWind** [comment]
I found the closed issue #130, it's an incompatibility because of that mod breaking tags. I'll look to have the mod removed from the pack, and if there aren't further updates this can be closed. Thanks for the communication and doing your best to help.

**Comment by PssbleTrngle** [comment]
Happy to help, yes that was also my suspicious, sadly eventhough this would be an easy fix, the twilight deslights mod has no received any updates in a long time
