### ISSUE TITLE
Custom Bucket Model 

### ISSUE THREAD

**Issue by f0kx** [PssbleTrngle/SliceAndDice#136]
### What happened?

The Texture of the Liquid is above the Bucket with Custom Model of another Texture pack

![image](https://github.com/PssbleTrngle/SliceAndDice/assets/14795020/19c3e5e3-721b-46af-a999-3f19c436c3cf)

### Loader

forge

### Mod Version

2.3.2

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
How do other modded buckets look like?

**Comment by f0kx** [comment]
in most mods i can change the bucket type or some other stuff ...but in your mod there is no "fert.bucket.png" to change that

**Comment by f0kx** [comment]
![image](https://github.com/PssbleTrngle/SliceAndDice/assets/14795020/fd6dea7d-787d-42aa-81d7-2d54c5aa7308)
here you see that your bucket is the only one which had the liquid not correctly

**Comment by f0kx** [comment]
the liquid is 2 pixel above the bucket...
and i cant change that because you dont have a file which does that

**Comment by PssbleTrngle** [comment]
The bucket model uses the built-in forge generated model, but you could overwrite it to use a custom texture using a resourcepack by modifying the `models/item/fertilizer_bucket.json` file
