### ISSUE TITLE
Readme links "example_datapack.zip" for adding shears in Forge, doesn't work in Fabric

### ISSUE THREAD

**Issue by ninjaeon** [PssbleTrngle/SliceAndDice#146]
### Describe the feature you have in mind.

Add a link in the readme to a separate "example_datapack.zip" that adds shears item tag in Fabric.

### Does this solve a particular problem?

I got the "example_datapack.zip" to allow shears in Fabric after editing allowed_tools.json contained in the zip to the following:
```
{
  "replace": false,
  "values": [
	{
	  "id": "#c:tools/knives",
	  "required": false
	},
	"#minecraft:axes",
	"minecraft:shears"
  ]
}
```

**Comment by PssbleTrngle** [comment]
Added a fabric version of the example pack, thanks for the notice
