### ISSUE TITLE
Farmer's Delight woodcutting compat

### ISSUE THREAD

**Issue by alfonsan** [PssbleTrngle/SliceAndDice#15]
### Describe the feature you have in mind.

When you use an axe to cut wood on the FD cutting board, you get the stripped version AND bark. I think that you could implement that mechanic the same way you actually implement knives for food.

Another angle for this solution could be to add the bark to the regular cutter table when you cut wood, I dont know if you could implement that one.

### Does this solve a particular problem?

Not a problem, but it has added value compared to the regular cutter from Create. 

This method gives bark that is a useful resource, while the regular create cutter does not.

**Comment by PssbleTrngle** [comment]
This is already happening, any recipe from the cutting board can be done using the slicer.
You only have to allow the tool type to be held by the slicer by adding it to the [tag](https://github.com/PssbleTrngle/SliceAndDice#automatic-cutting)
