### ISSUE TITLE
Add breaks farmersdelight <= 1.20.1-1.4.3 to FMJ

### ISSUE THREAD

**Issue by Poopooracoocoo** [PssbleTrngle/SliceAndDice#151]
### Describe the feature you have in mind.

This'll prompt users to install Farmers Delight Refabricated without the game crashing.

````
  "breaks": {
    "farmersdelight": "<1.20.1-2.0.0"
````

Would also work

And while you're at it, you can switch to the newer `fabric-api` mod ID!

https://github.com/PssbleTrngle/SliceAndDice-Fabric/blob/1.20.x/src/main/resources/fabric.mod.json

### Does this solve a particular problem?

A lot of people have been downloading Farmers Delight [Fabric] and the latest version of Create Slice and Dice, not knowing that newer versions of Create Slice and Dice only support Farmers Delight Refabricated.

**Comment by Poopooracoocoo** [comment]
Despite FDR being marked as an optional dependency on CurseForge and Modrinth, Create Slice and Dice actually crashes when no Farmer's Delight mod is present. 

That means there should either be a dependency on FDR, or that there's a bug that needs to be fixed.

**Comment by PssbleTrngle** [comment]
Good idea, thank you. Should also definitely not break without farmers delight, that is a bug which will be fixed
