### ISSUE TITLE
Mixin breaks default harvester functionality

### ISSUE THREAD

**Issue by voodoofrog** [PssbleTrngle/SliceAndDice#153]
### What happened?

The mixin for the harvester block prevents the harvester using shears on leaf blocks, thus preventing the default Create functionality of leaf harvesting.

### Loader

fabric

### Mod Version

3.2.2

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
On it, and I somehow also forgot to port that feature to the 1.19 & 1.20 branches
