### ISSUE TITLE
Slicer doesnt accept axe after first axe breaks

### ISSUE THREAD

**Issue by Plasman888** [PssbleTrngle/SliceAndDice#157]
### What happened?

When first placed the slicer accepts axe from hopper but after the initial axe breaks it no longer accepts axes unless the slicer is broken and placed again. https://outplayed.tv/media/MwxzkN

### Loader

fabric

### Mod Version

1.20.1 3.2.3

### Minecraft Version

1.20

**Comment by Plasman888** [comment]
https://outplayed.tv/media/MwxzkN

**Comment by PssbleTrngle** [comment]
Has been resolved in dev and will be fixed in the next release
