### ISSUE TITLE
Slicer to deplete tool durability

### ISSUE THREAD

**Issue by OffBy0x01** [PssbleTrngle/SliceAndDice#16]
### Describe the feature you have in mind.

Currently there is no incentive to use higher tool tiers with the slicer as tool durability is not depleted by uses. Functionally a wooden axe or flint knife works the same as its netherite equivalents, forever.

Late game crushing always produces lots of flint which is otherwise wasted - automating the supply of flint knives to feed the slicer would be a fun way to make use of some of it.

### Does this solve a particular problem?

Love the idea of the slicer - I hate the way deployers interact with chopping boards, however without durability affects it is unbalanced.

**Comment by AlisonHuang777** [comment]
Has this feature implemented?

**Comment by AlexTheDolphin0** [comment]
> Has this feature implemented?

Just checked in 3.2.0 for forge 1.20.1, and that's a no.

**Comment by PssbleTrngle** [comment]
It actually has been implemented, just need to enable it in the server config. I don't know why I never mentioned it here & closed this issue
