### ISSUE TITLE
Sprinkler limitation?

### ISSUE THREAD

**Issue by Bebobobo** [PssbleTrngle/SliceAndDice#163]
### What happened?

If i connect more than 2 sprinklers only the closest 2 from the water source function. Is this a limitation of sprinklers?

![image](https://github.com/user-attachments/assets/58f12272-7c73-4bb5-84df-2f8700f2c077)

### Loader

forge

### Mod Version

3.2.1

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Seems like the last two don't receive any water, does it work if you increase the rotation speed of the pump?

**Comment by Bebobobo** [comment]
yes i used the creative motor set to 64 and it still only pumped enough for the 2 sprinklers. when i switched over to thermal expansion ducts it worked just fine even at the default waterwheel rotation.

**Comment by Bebobobo** [comment]
Did some more testing. default speed with 2 water wheels only. Hope this helps.

![image](https://github.com/user-attachments/assets/b7cbc647-9496-46e9-ad9e-2708cc356e00)
![image](https://github.com/user-attachments/assets/0f2837ac-537b-4f08-af2b-f619a34989f5)
![image](https://github.com/user-attachments/assets/4c31e8c8-85bc-4f45-bd88-46cca0b90982)
![image](https://github.com/user-attachments/assets/12bc8202-084f-4aff-899f-37a1c41fd123)

**Comment by ZeuxDEV** [comment]
looks to me like its the pumps 16 block limit, pumps can push and pull water only for 16 blocks in either direction. that you use non-create pipes messes with this, i think.

**Comment by Bebobobo** [comment]
i was not aware of this. Thank you for the info. Consider this closed.
