### ISSUE TITLE
Knife durability is not consumed

### ISSUE THREAD

**Issue by LioxAcc** [PssbleTrngle/SliceAndDice#165]
### What happened?

Knife's durability is not consumed when you use it with the slicer
This is a duplicate of [issue #16](https://github.com/PssbleTrngle/SliceAndDice/issues/16)
I checked the config. 
"consume_tool_durability" is set to true (as it comes by default)
I also tested it by changing this to false (just in case)
The result was the same

### Loader

forge

### Mod Version

sliceanddice-forge-3.2.1

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
This is because if (for some reason) only applied durability damage for slicers operating on a basin, will be fixed in the next release
