### ISSUE TITLE
Make buckets not get consumed in mixing recipes

### ISSUE THREAD

**Issue by TriibuNupsik** [PssbleTrngle/SliceAndDice#167]
### Describe the feature you have in mind.

Recipes like the mashed potato one require a milk bucket but then the bucket gets consumed.

Solutions:
1. Make the bucket not get consumed
2. Swap the requirement with milk fluid

### Does this solve a particular problem?

It makes buckets not get consumed in mixing recipes because it's weird when the bucket gets mixed in my food.

**Comment by PssbleTrngle** [comment]
This is a duplicate of #108, I will address it there
