### ISSUE TITLE
Can't disable some categories of recipes

### ISSUE THREAD

**Issue by Barerock** [PssbleTrngle/SliceAndDice#172]
### What happened?

I'm trying to disable some mixing recipes configured through sliceanddice, but I just can't. Either through regex or simply removing every mixing recipe from sliceanddice, KubeJS can't seem to do it. I've used code from other people that's supposed to work, even removing recipes via datapack doesn't work. This is also the case for Vinery, so I'm unsure whether this is a Create issue or not. it's very frustrating since I also can't remove individual recipes. The IDs just don't work at all.

### Loader

forge

### Mod Version

3.3.0

### Minecraft Version

1.20

**Comment by Barerock** [comment]
Small detail, I tried removing EVERY mixing recipe via modid and type in kjs, but that removed THREE recipes out of about 100 total. I specifically want to remove vintagedelight and mynethersdelight from support.

**Comment by Barerock** [comment]
This has turned into a wild goose chase for another mod using many many many scripts and formats and even crafttweaker to disable these. I think this is a create issue.

**Comment by PssbleTrngle** [comment]
You can disable the automatic conversion of cooking recipes to mixing recipes by giving them an ID ending with "_manual_only" (works for creative shapeless mixing too btw)

**Comment by Barerock** [comment]
Well I found that altering the data in general seemed dubious. I managed to use CraftTweaker with some help to disable some things. Still don't know why KubeJS had issues. This is otherwise solved, just not elegantly.

**Comment by PssbleTrngle** [comment]
Altering/Disabling the mixing recipes is generally not easy or reliable, it's intended to either:
A) disable or alter the cooking recipe itself, causing the same to the mixing recipe or
B) using the `_manuel_only` suffix
