### ISSUE TITLE
Add recipes to mechanical saw/deployer instead of slicer?

### ISSUE THREAD

**Issue by archonxgames** [PssbleTrngle/SliceAndDice#19]
### Describe the feature you have in mind.

Would it be possible to have the slicer disabled in the config and have the recipes that wouldve otherwise been used with the slicer be added into the mechanical saw instead? For example, having the log stripping recipe used by the mechanical saw be adjusted to output the farmer's delight bark as well.

### Does this solve a particular problem?

I feel like the slicer is redundant considering that mechanical saws already exist which serves as a "slicer" in a way. The features this mod adds actually makes sense and fills a lot of the gaps in game, but I feel like the slicer's functionality could just be added in a more natural fashion with the mechanical saw (or hell, maybe used with the mechanical arm/deployer and a knife/axe)

**Comment by PssbleTrngle** [comment]
I have  thought about that at first, but it would conflict with existing recipes for the mechanical saw and would only make sense for a handful of recipes. 
The mechanical saw can also only output 1 itemstack per recipe, making recipes like the wood stripping including bark impossible.

If you still want to do this, adding recipes to the mechanical saw is entirely possible (yet a bit tedious for so many recipes) using datapacks or a mod like kubejs/crafttweaker

**Comment by PssbleTrngle** [comment]
I am pretty sure the deployer also only allows a single output
