### ISSUE TITLE
Mod "has failed to load correctly"

### ISSUE THREAD

**Issue by Marksman12** [PssbleTrngle/SliceAndDice#20]
### What happened?

As the title says, the mod straight up doesn't seem to want to load. I'll leave the full log here.

[crash-2022-11-29_05.44.02-fml-copy.txt](https://github.com/PssbleTrngle/SliceAndDice/files/10112679/crash-2022-11-29_05.44.02-fml-copy.txt)

### Mod Version

Version 2.0.0 (MC 1.19.2)

### Forge Version

43.1.52

**Comment by PssbleTrngle** [comment]
Pretty sure you are missing [kotlin for forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)

**Comment by Marksman12** [comment]
Oh woops, yeah that was the issue xd
Thanks! I'll be more careful from now on
