### ISSUE TITLE
[1.18.2, Forge] tag minecraft:water used on Liquid Fertilizer

### ISSUE THREAD

**Issue by HonzaVinCZ** [PssbleTrngle/SliceAndDice#23]
### What happened?

Please, refer to this issue (fluid Liquid Fertilizer involved): https://github.com/Creators-of-Create/Create/issues/4203

### Mod Version

sliceanddice-1.1.0

### Minecraft Version

1.18

### Forge Version

40.1.86

**Comment by PssbleTrngle** [comment]
I am a bit uncertain about this on, because on the one hand the recipe stuff is pretty annoying, but on the other hand, what the person on the create team said is also true.
