### ISSUE TITLE
Exit Code 1 crash with no log

### ISSUE THREAD

**Issue by TheDoctor1977** [PssbleTrngle/SliceAndDice#24]
### What happened?

Installed this, Kotlin (3.8.0) and Create (0.5.0c) and the game crashes on launch with no crash log and Exit Code 1.
I have other mods, but they are not relevant to this mod and its dependencies.
Edit: Just launched with no changes except removing this mod and the crash did not occur, so it's not Kotlin or Create.

### Mod Version

1.1.0

### Minecraft Version

1.18

### Forge Version

40.1.92

### Relevant log output

```shell
N/A
```

**Comment by PssbleTrngle** [comment]
is there no `latest.log` file being created when you launch?
