### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by MagmaSlime123** [PssbleTrngle/SliceAndDice#26]
### What happened?

Title.

### Mod Version

2.0.0.

### Minecraft Version

None

### Forge Version

43.2.3. Add 1.19.2 to the MC version selection.

### Relevant log output

```shell
https://pastebin.com/U9m5MvAp
```

**Comment by PssbleTrngle** [comment]
You're missing "kotlin for forge"

**Comment by PssbleTrngle** [comment]
You're missing "kotlin for forge"

**Comment by MagmaSlime123** [comment]
Description never mentioned this.
