### ISSUE TITLE
Slicer should only work when rotating in the correct direction

### ISSUE THREAD

**Issue by albertosaurio65** [PssbleTrngle/SliceAndDice#4]
### Describe the feature you have in mind.

1. You need 4 knives in inventory to put all 4, the less knives you have the longer it takes regardless of rotation speed
2.It only works if it turns in the proper direction with the tilt of the knife. 
![image](https://user-images.githubusercontent.com/70109413/185664327-f07c22b7-ac3c-44fc-be45-73f6936df5fe.png)

**Comment by PssbleTrngle** [comment]
1) I was thinking about the knife things, but it feels like it would be a user-interaction hell
2) The rotation thing being backwards is a bit weird, but it would also be weird if it would not rotate in the same direction as the cog, but I can give it a try

**Comment by albertosaurio65** [comment]
1.yeah, if it is very complicated it does not matter, it is just a detail
2.The create + pressurecraft addon makes it only work if it spins in a certain direction, so if the person spins in the wrong direction it could stop, otherwise all very well, it just seemed strange to me that it turned in the other direction

**Comment by PssbleTrngle** [comment]
Making it only work if it spins in the correct direction sounds like a good idea

**Comment by PssbleTrngle** [comment]
Will be included in the next release
