### ISSUE TITLE
Pondering Sprinklers

### ISSUE THREAD

**Issue by gigawhip** [PssbleTrngle/SliceAndDice#40]
### Describe the feature you have in mind.

A multi-stage Ponder scene explaining core concepts. From the [README](https://github.com/PssbleTrngle/SliceAndDice/tree/d66036b280c4c505124231856b80e14bab26df00#sprinkler): 

- When provided with a fluid using a pipe, will distribute it in a small area below.
- Lava applies a small amount of fire damage to entities below.
- Water makes the area below wet, making the world think it's raining there.
- Potions apply their affect for a short duration to entities below.
- Liquid Fertilizer, a new fluid, applies a bonemeal affect to blocks.

### Does this solve a particular problem?

It solves a UX issue. Create teaches its users that Create-compatible items are the ones that have Ponders. Not having a Ponder indicates that an item is not designed to be used with Create.

It also adds polish to this excellent mod of yours.

**Comment by zachsai** [comment]
I also agree this should be a thing

**Comment by PssbleTrngle** [comment]
Added two ponder scenes in the latest release. I have not added one for the fertilizer specifically, but you also get the same ponders when you hover over the bucket, so I feel like the player should be able to connect these things
