### ISSUE TITLE
Slicer doesn’t accept anything

### ISSUE THREAD

**Issue by firemaster1294** [PssbleTrngle/SliceAndDice#42]
### What happened?

I assembled a slicer using the newest version of slice and dice and it is refusing to accept literally anything when I right click it. Is this a known bug with the most recent release?

### Mod Version

1.1.3

### Minecraft Version

1.18

### Forge Version

40.2.0

**Comment by PssbleTrngle** [comment]
Is this still happening in the newest version?

**Comment by firemaster1294** [comment]
I isolated the issue to Twilight Delight messing up some tags in 18.2

**Comment by PssbleTrngle** [comment]
Ah yes, that's also the issue with #7, but the Twilight Delight team has not been working on their mod for about a year now

**Comment by firemaster1294** [comment]
I will note - I was able to override the item tags using KubeJS and it fixed the issue
