### ISSUE TITLE
1.18.2 bug fix parity

### ISSUE THREAD

**Issue by blake-lowe** [PssbleTrngle/SliceAndDice#43]
### What happened?

Hi there, I see that you've fixed the pondering and related crashes on the 1.19 version of the mod. Is there any chance you can update the 1.18.2 version with this fix. I know many people use 1.18.2 as a stable modding version. Thank you!

### Mod Version

1.1.3

### Minecraft Version

1.18

### Forge Version

40.2.0

**Comment by PssbleTrngle** [comment]
It should also be fixed in the 1.18.2 version, is the crash still happening for you?
