### ISSUE TITLE
(1.18.2) Error loading datapack preventing world create/load

### ISSUE THREAD

**Issue by TheSpartan696** [PssbleTrngle/SliceAndDice#44]
### What happened?

I cant load into world or create a world
![Screenshot 2023-03-16 014019](https://user-images.githubusercontent.com/127004713/225525180-cc95dba2-3fe3-4490-806b-20dc9e99df13.png)

### Mod Version

1.1.3

### Minecraft Version

1.18

### Forge Version

40.2.1

**Comment by PssbleTrngle** [comment]
Can you post the log?

**Comment by TheSpartan696** [comment]
It only happens on world load or create, there is no log.
