### ISSUE TITLE
Slicer cannot be filled with a mechanical arm and cranky from deployer

### ISSUE THREAD

**Issue by Urmus-dev** [PssbleTrngle/SliceAndDice#45]
### What happened?

To automate slicer, we can only use deployer, but the deployer keeps removing the knife present on the slicer and replace it with a new one, which is confusing and looks weird.
A mechanical arm cannot use slicer as target, and hopper doesn't seem to work either.

That said, it feels not integrated in Create factories, I consider disabling tool durability decrease to automate my farm :)

### Mod Version

2.0.0

### Minecraft Version

None

### Forge Version

43.2.8

**Comment by PssbleTrngle** [comment]
Has been implemented in the latest release
