### ISSUE TITLE
how to add shears to the slicer?

### ISSUE THREAD

**Issue by lolzhunter** [PssbleTrngle/SliceAndDice#46]
### What happened?

might be a bit silly but im on the latest version, and there is no client config or an option in the common config to edit what the slicer can use as a tool
![image](https://user-images.githubusercontent.com/51302861/230678042-aeaccf2e-5ea2-4067-b16a-4a60419f171d.png)
![image](https://user-images.githubusercontent.com/51302861/230678578-e19a98e8-2501-4960-a67e-20c4fdf7e5d6.png)
i am using this in a custom curseforge modpack based off of "create flavored" with some added mods like thermal series and ae2 for 1.19.2 to name a few.
i suppose my question is can i manually add the config back or am i doing something wrong, trying to cut up leather armor on a conveyor belt but the knives dont work so i figured i needed shears but couldnt put them on the slicer, i was using the beta version of 1.19 figured that was the issue, updated to 2.0.3 but still no added config/problem still happening, tried repairing the modpack still didnt fix it. any advice?

### Mod Version

2.0.3

### Minecraft Version

None

### Forge Version

43.2.4

**Comment by lolzhunter** [comment]
not sure why available recipes in the JEI [tools] aren't auto added :/, then again that feature could be annoying af to code/maintain i wouldnt know, knives and axe works fine so i know the list exists _somewhere_

**Comment by PssbleTrngle** [comment]
The list of tools that are possible to be put into a slicer is managed using an item tag, it's explained [here](https://github.com/PssbleTrngle/SliceAndDice#automatic-cutting)

**Comment by lolzhunter** [comment]
yes, but where/how do i do that? could you link a more in depth guide if possible

EDIT:
managed to figure it out, had to go into the jar directly to find the allowed tools json and edited it so it looks like this now
![image](https://user-images.githubusercontent.com/51302861/230735919-72c7a469-c4a7-433d-81ac-b43488f3c259.png)
wish there was a easier way to do it but oh well, it did work, was able to boot into a world and it worked with the shears and the leather armor processing and all that

**Comment by PssbleTrngle** [comment]
There is an easier way than to edit the file within the jar, it's [datapacks](https://minecraft.fandom.com/wiki/Data_pack)

**Comment by lolzhunter** [comment]
my datapacks folder is empty for the world im using and the data folder doesnt have anything about create slice and dice

**Comment by lolzhunter** [comment]
![image](https://user-images.githubusercontent.com/51302861/230753764-701c6a35-25e0-423f-8d0c-af0a09f825fa.png)

**Comment by PssbleTrngle** [comment]
Yes, you would have to create a datapack in that folder, they work similar to resource pack, but instead of modifying textures/models, they can modify things like recipes & item tags

**Comment by lolzhunter** [comment]
huh, how would i go about that for future reference? sorry ive never used datapacks before

**Comment by PssbleTrngle** [comment]
I recommend you watch a youtube tutorial on datapack.
An basic example datapack which you could place in your worlds "datapacks" folder that adds shears would be this:
[example_datapack.zip](https://github.com/PssbleTrngle/SliceAndDice/files/11219813/example_datapack.zip)
