### ISSUE TITLE
Game not loading - 1.19.2

### ISSUE THREAD

**Issue by kajussls121** [PssbleTrngle/SliceAndDice#49]
### What happened?

Game not loading on 1.19.2, shows java.lang.reflect.InvocationTargetException: null, same thing with server 
![image](https://user-images.githubusercontent.com/82109610/232250914-0d0de120-0bfb-4b96-ae34-2fc83873b7a3.png)

### Mod Version

2.0.3

### Minecraft Version

None

### Forge Version

43.2.0

**Comment by PssbleTrngle** [comment]
Without the log I cannot do a lot, but the probable problem is that you're missing [kotlin for forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)

**Comment by kajussls121** [comment]
Yeah, I do not have kotlin thanks, would be great if it shows this mod requires kotlin instead of erroring out like:
![image](https://user-images.githubusercontent.com/82109610/233096541-ae4bb0cc-d0f7-4ca9-a9bb-8b04d692ee81.png)
