### ISSUE TITLE
Compatibility with Create 0.5.0c

### ISSUE THREAD

**Issue by ordinarylemon** [PssbleTrngle/SliceAndDice#5]
### Describe the feature you have in mind.

Would it be possible to add compatibility with Create 0.5.0c? I would update to the newer version but it doesn't work with optifine as it requires a newer forge version, and the newer forge version is incompatible with optifine.

**Comment by PssbleTrngle** [comment]
Backporting this to an earlier create version is not intended, optifine will surely update to some time soon

**Comment by PssbleTrngle** [comment]
Until then, you could also try some optifine alternatives that are not known to regularly break other mods 😉
