### ISSUE TITLE
Please let us orient the tools on the slicer so they can work regardless of where it's rotating

### ISSUE THREAD

**Issue by AnasterianSunstrider** [PssbleTrngle/SliceAndDice#50]
### Describe the feature you have in mind.

Currently if we place two slicers next to each other, only one of them will work because the other will rotate in the opposite way. If we only place one but it's rotating the wrong way, we have to change the setup even though mixers do not have this issue. If we could orient the tools on the slicer in the opposite direction with a wrench it would make setups way easier.

**Comment by PssbleTrngle** [comment]
You can also disable the required correct direction in the config file
