### ISSUE TITLE
1.16.5

### ISSUE THREAD

**Issue by DogToy** [PssbleTrngle/SliceAndDice#52]
### Describe the feature you have in mind.

I would like the mod to be available in 1.16.5.

### Does this solve a particular problem?

I run a server with other mods like create and farmers delight. I really want this mod for my server and a lot of other people who use 1.16.5 mods that are not in 1.18+ would like this.

**Comment by PssbleTrngle** [comment]
I think that's very unlikely, since probably a lot of internal code has changed between 1.16 - 1.18.
Also implementing it for 1.16 would also mean maintaining an additional version

**Comment by DogToy** [comment]
Thanks.
