### ISSUE TITLE
Missing bucket of liquid fertilizer model

### ISSUE THREAD

**Issue by SplendidAlakey** [PssbleTrngle/SliceAndDice#54]
### What happened?

The bucket of liquid fertilizer model is missing.

Edit: the issue goes away after reloading resources

![2023-05-05_02 27 32](https://user-images.githubusercontent.com/86702831/236356712-5e64e471-5b32-4625-954c-117b1bf816b8.png)

![2023-05-05_02 27 45](https://user-images.githubusercontent.com/86702831/236356723-5a01dfee-ebc5-405f-be97-72e3c02f6f34.png)

### Loader

fabric

### Mod Version

2.1.1

### Minecraft Version

1.19

### Relevant log output

```shell
https://gist.github.com/SplendidAlakey/d76781150e35c3a2d4d942b34ca4f2db
```

**Comment by PssbleTrngle** [comment]
Added a texture in version 2.1.2
