### ISSUE TITLE
Sprinkler boost plant growth

### ISSUE THREAD

**Issue by MKMKLMLM** [PssbleTrngle/SliceAndDice#6]
Is there any chance of Sprinkler spraying liquid（water? or other liquid）to boost plant growth randomly,just like rich soil in 
FarmersDelight? I think it will make it more valuable.

**Comment by PssbleTrngle** [comment]
True, the use cases of the sprinkler are edge cases right now, to be honest I only created it for the neapolitan compatibility.
But I also designed them to be easily extended with additional functionality.

Boosting crop growth could certainly be a good feature, but I would like it to be boosted by some sort of liquid fertilizer and not just water

**Comment by traveldesign** [comment]
Would it be possible for the sprinkler to hydrate farmland? It would be cool for greenhouses.

**Comment by PssbleTrngle** [comment]
I have just realised that sprinklers already hydrate farmland, since farmland gets slowly hydrated in the rain, and a sprinkler with water simulates the rain

**Comment by PssbleTrngle** [comment]
Added liquid fertilizer in `1.1.0` which can be used to boost crop growth
