### ISSUE TITLE
Mod converts recipes with a _manual_only ID suffix

### ISSUE THREAD

**Issue by Treeways** [PssbleTrngle/SliceAndDice#65]
### What happened?

I'm trying to fix a specific recipe that has to do with cooking with a water bucket. These water bucket recipes are bugged in my modpack, and duplicates the bucket.
(See https://github.com/Creators-of-Create/Create/issues/4701)

In base Create mod, specific recipes will not be autogenerated by Create when the `_manual_only` suffix is detected in its recipe ID. For example, it will stop Shapeless recipes from generating Automated Mixing Recipes (and vice versa for Shaped/Automated Shaped Crafting), like so:

![image](https://github.com/PssbleTrngle/SliceAndDice/assets/56928485/98243b58-3fee-43f1-9e2d-5bfb59cc44b6)

Example:
`delightful:food/marshmallow_stick`: Create will generate an Automated Shapeless recipe from this original recipe.
`delightful:food/marshmallow_stick_manual_only`: Create will NOT generate an Automated Shapeless recipe for this.

---------

I was able to override the *original* cooking pot recipe to change the ID to `kubejs:nut_milk_manual_only`, but it did not prevent Slice and Dice from autogenerating a mixing recipe.

Currently, Slice and Dice ignores this suffix and generates mixing/slicing recipes despite this.

![image](https://github.com/PssbleTrngle/SliceAndDice/assets/56928485/b8c79b2d-4ea5-4c7b-85f4-2a1ff7d18eda)

![image](https://github.com/PssbleTrngle/SliceAndDice/assets/56928485/b0c74380-093c-4b25-a5fd-1cd11a8c32e5)

### Loader

forge

### Mod Version

2.0.3

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
Oh I did not know create was filtering out recipe with this suffix, but that makes sense, will add this in the next release
