### ISSUE TITLE
Slice and Dice Not Compatible with Create .5.1.a Update

### ISSUE THREAD

**Issue by ClaudiusMinimus** [PssbleTrngle/SliceAndDice#68]
### What happened?

Slice and Dice version sliceanddice-forge-2.1.1-forge.jar is not compatible with the new Create .5.1.a update.
![image](https://github.com/PssbleTrngle/SliceAndDice/assets/17887664/15c70a83-bdf4-41ea-a998-8940761372b5)

### Loader

forge

### Mod Version

sliceanddice-forge-2.1.1-forge.jar 

### Minecraft Version

1.19

**Comment by muriplz** [comment]
https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry/issues/72
https://github.com/talrey/CreateDeco/issues/80
