### ISSUE TITLE
latest 2.2.0 crashing on launch

### ISSUE THREAD

**Issue by DadoIrie** [PssbleTrngle/SliceAndDice#69]
### What happened?

title says pretty much everything and I'm countless time checking if I've missed something and even made a separate instance in order to tackle tackle it down and seeing what the conflict might be and ended up with only `create-1.19.2-0.5.1.a, FarmersDelight-1.19-1.2.1, kotlinforforge-3.12.0-all, overweightfarming-1.19.2-2.0.1-forge, sliceanddice-forge-2.2.0` and still crashing - overweight farming I added later on just to see if that could be the missing piece - nope, still crashing
am I'm doing something wrong here?

### Loader

forge 43.2.3

### Mod Version

2.2.0

### Minecraft Version

1.19.2

### Relevant log output

```shell
https://mclo.gs/oQQ2Fz6
```

**Comment by PssbleTrngle** [comment]
See #70

**Comment by DadoIrie** [comment]
I did download it from curseforge and not using the GitHub if that's what you're suggesting 

EDIT/UPDATE: but since I'm not at home right now I'll download the new build from curse and see if the issue is resolved as soon I'm home

**Comment by DadoIrie** [comment]
fixed with the new build - thanks - closing
