### ISSUE TITLE
The Slicers doesn't work when other Farmer's delights addons are added

### ISSUE THREAD

**Issue by Greg727** [PssbleTrngle/SliceAndDice#7]
### What happened?

I was making a create mod pack with your mod and I added Farmer's delight and it's various addons for Version 1.18.2

But in doing so, The slicer no longer seems to be working

Works just fine when it's simply Create and Farmer's Delight, but with Farmer's Delight Addons not so much.

### Mod Version

sliceanddice-1.0.2.jar

### Minecraft Version

1.18

### Forge Version

Forge-40.1.73

**Comment by PssbleTrngle** [comment]
Which addons specifically, because it does work with cultural delights for me

**Comment by Greg727** [comment]
This list should help you. Also I forgot to mention that the problem is that the slicer won't equip the knife no matter how many times I right click.

### **Addons that work fine**
Abnormals Delight
Alex's Delight
Betta's Delight
Butcher's Delight
Corn Delight
Cultural Delight
Delightful
Dracovita Delight
Farmer's Respite
Honey Expansion
Large Meals
Nether's Delight
Vegetarian Delight

### **Addons with issues**

Gobber Delight (The knifes that come with this specific mod don't get accepted by the slicer, but the other knifes from the other addons get accepted just fine, so there is no issue there.)

Twilight Delight (This one is the main problem. When loaded, the slicer doesn't accept any knifes at all, no matter which mod it comes from. And before you ask, no the issue isn't with the Twilight Forest mod. I tested it with Twilight Forest and the slicer works just fine. It's the mods specific addon that's the problem.)

**Comment by PssbleTrngle** [comment]
Look like Gobber Delight is not adding it's knife to the `farmersdelights:tools/knives`  item tag, which you could also resolve by adding it using a datapack.

The issue with Twilight Delight sounds like something in their `farmersdelights:tools/knives` file is incorrect, removing the entire tag. Can you send me your `latest.log` file?

**Comment by Greg727** [comment]
[latest.log](https://github.com/PssbleTrngle/SliceAndDice/files/9482776/latest.log)

**Comment by PssbleTrngle** [comment]
Ok, it is indeed a similar problem, but a bit more stuff is happening, I'm gonna open an issue on on the TwilightDelight repo

**Comment by PssbleTrngle** [comment]
Wait, which version of the TwilightDelight mod are you using?
It says in the log that you are using the pre-release `1.2.0-Alpha`, but there is already a release version of the mod that fixed that bug

**Comment by Greg727** [comment]
Yeah that's right I am using 1.2.0-alpha.

**Comment by PssbleTrngle** [comment]
Why are you using an outdated alpha version if there is a newer release version?

**Comment by PssbleTrngle** [comment]
Why are you using an outdated alpha version if there is a newer release version?

**Comment by Greg727** [comment]
If your talking about the release it already has for 1.18.2, that's 1.1.4.jar

If your talking about one that's above 1.2.0, then it isn't on curseforge

**Comment by PssbleTrngle** [comment]
Ah sorry, I switched some number around in my head.
Still weird though, because it looks like they never had that issue in their code, but the released mod jar has different values.
I opened an issue [here](https://github.com/Laokuai233/Twilight-Delight/issues/26)

**Comment by Junnaturefox** [comment]
The Twilight Delight dev team actually released version 1.2.0-Beta of the mod on August 5th on mcmod.com (a Chinese minecraft mod site), but it still doesn't work with Slicers.
Unfortunately, the members of their development team are all students, and in China, high schools usually start in mid-August, so they probably don't have much time to works on this mod.

**Comment by PssbleTrngle** [comment]
I am pretty sure they have also already fixed the issue in their code a few days ago, but there has not been a release since that

**Comment by PssbleTrngle** [comment]
I'll close this issue, since there is nothing wrong on Slice & Dice's end
