### ISSUE TITLE
Not doing recipes added by craft tweaker

### ISSUE THREAD

**Issue by gourd-ne** [PssbleTrngle/SliceAndDice#71]
### What happened?

In craft tweaker, I have this script set up:

`<recipetype:farmersdelight:cutting>.addRecipe("cut_slice_of_bread", <item:minecraft:bread>, [<item:kubejs:slice_of_bread> * 4], <tag:items:farmersdelight:tools/knives>, "minecraft:block.gravel.break");`

That script works fine on the cutting board, but it isn't working with the slicer. The item will just pass on by on the conveyor belt without doing anything, though the slicer still works for base recipes added by other mods. It isn't a kubejs custom item problem since it doesn't work for other recipes either.

### Loader

forge

### Mod Version

1.1.3

### Minecraft Version

1.18

**Comment by PssbleTrngle** [comment]
I also had to mixin into a KubeJS class to get it working together with that, I guess I would need a similar solution for crafttweaker. What you could do I think, is add the recipe "manually" through craftweaker to "sliceanddice:cutting" as well

**Comment by gourd-ne** [comment]
Thanks for the clarification. If it works with KubeJS, I'll just use KubeJS for cutting board recipes - I'm sure it's not too difficult of a switch.
