### ISSUE TITLE
Update 1.18.2 for Create 0.5.1

### ISSUE THREAD

**Issue by CrusaderRabbit** [PssbleTrngle/SliceAndDice#72]
### What happened?

This was updated to be compatible for 1.19.2 but Create still updates for 1.18.2 as well. Can this be updated as well?

### Loader

forge

### Mod Version

1.1.3

### Minecraft Version

1.18

**Comment by Lilygabe** [comment]
I agree with this

**Comment by ClashofCraft972** [comment]
Yes, it would be cool please, agreed :)

**Comment by Reshy** [comment]
Crash Log:  https://pastebin.com/TEK8Wwbi

**Comment by PssbleTrngle** [comment]
In the work 👍

**Comment by PssbleTrngle** [comment]
Update is out, I hope everything works
