### ISSUE TITLE
Invalid Class Reference/Mixin Target

### ISSUE THREAD

**Issue by rinebergc** [PssbleTrngle/SliceAndDice#75]
### What happened?

Mod will throw a warning is KubeJS is missing. The warning goes away if KubeJS is installed.
Mod should not make class reference to/target another mod, unless such mod is a dependency.

### Loader

fabric

### Mod Version

2.1.3

### Minecraft Version

1.19

### Relevant log output

```shell
[main/WARN]: Error loading class: dev/latvian/mods/kubejs/recipe/RecipesEventJS (java.lang.ClassNotFoundException: dev/latvian/mods/kubejs/recipe/RecipesEventJS)

[main/WARN]: @Mixin target dev.latvian.mods.kubejs.recipe.RecipesEventJS was not found sliceanddice.mixins.json:RecipeEventJSMixin from mod sliceanddice
```

**Comment by PssbleTrngle** [comment]
Yes, this is intentional, since it's an optional mixin into a KubeJS class, which will print a warning if it fails

**Comment by Xyphenore** [comment]
I don't know how mixins work in mods. But isn't it possible to display an information instead of a warning, to indicate that KubeJS is missing and the mod doesn't load the extra recipes?

**Comment by PssbleTrngle** [comment]
The mod still works if KubeJS is missing, the mixin is only there to make it work if kubejs is present too.
And there would probably a way to somehow hide it but that would be way to much effort just to hide one warning in the log, especially since modpacks usually print a ton of warnings anyway
