### ISSUE TITLE
Unable to give Slicer tool automatically

### ISSUE THREAD

**Issue by teenangst** [PssbleTrngle/SliceAndDice#76]
### What happened?

When a tool is used up I'm unable to give it an item automatically to be able to continue. I have to give it a tool manually every time one is used up

I've tried:

- Chute
- Hopper
- Funnel
- Mechanical Arm

### Loader

forge

### Mod Version

1.2.0

### Minecraft Version

1.18

**Comment by PssbleTrngle** [comment]
You're right, I think I forgot something when I backplates the arm interaction from 1.19

**Comment by PssbleTrngle** [comment]
Should be fixed in 1.2.1

**Comment by teenangst** [comment]
Thank you so much

**Comment by Plasman888** [comment]
it isnt fixed for me

**Comment by PssbleTrngle** [comment]
@Plasman888 if that's the case, please open a new issue with your specified environment
