### ISSUE TITLE
sprinklers dont require liquid after filling up

### ISSUE THREAD

**Issue by Douche-Box** [PssbleTrngle/SliceAndDice#78]
### What happened?

when filling a sprinkler it doesnt require more liquid afterwards

### Loader

fabric

### Mod Version

2.1.3

### Minecraft Version

1.19

**Comment by NolanHewitt** [comment]
Can confirm this. You essentially get unlimited, which is pretty overpowered with the liquid fertilizer.

**Comment by JiDW** [comment]
Indeed, we can't install it for now as it is too OP for our server, but other than that the mod looks amazing and we can't wait to use it, gj!

**Comment by PssbleTrngle** [comment]
This only happens on fabric right?

**Comment by PssbleTrngle** [comment]
Should be fixed in the latest release
