### ISSUE TITLE
possible config error while trying to startup game

### ISSUE THREAD

**Issue by Douche-Box** [PssbleTrngle/SliceAndDice#79]
### What happened?

game crashes on startup possibly due to other mods but removing create slice and dice removes the issue

### Loader

fabric

### Mod Version

2.1.4

### Minecraft Version

1.19

### Relevant log output

```shell
The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Config not yet available
```

**Comment by PssbleTrngle** [comment]
Weird, can you share the entire logfile?

**Comment by Crasben** [comment]
I'm having the same problem, i added the mod in the modpack StaTech Industry

**Comment by Douche-Box** [comment]
this is the crash without any of the non necessary mods except  the "essential" mod

[crash-2023-06-03_23.49.47-client.txt](https://github.com/PssbleTrngle/SliceAndDice/files/11644334/crash-2023-06-03_23.49.47-client.txt)

**Comment by NolanHewitt** [comment]
Same issue here. 2.1.3 (fabric) version of this mod works perfectly, but the 2.1.4 version crashes on start up.

**Comment by PssbleTrngle** [comment]
Sounds like the same as #80
