### ISSUE TITLE
Dough tag is invalidated (fabric)

### ISSUE THREAD

**Issue by sisby-folk** [PssbleTrngle/SliceAndDice#81]
### What happened?

Due to an invalid reference to `#forge:dough/wheat` that I can assume is fabric specific, the c:dough tag fails to load.

### Loader

fabric

### Mod Version

2.1.3

### Minecraft Version

1.19

### Relevant log output

```shell
`[13:25:20] [Render thread/ERROR]: Couldn't load tag c:dough as it is missing following references: #forge:dough/wheat (from Create Slice & Dice)`
```

**Comment by sisby-folk** [comment]
hm, does this issue also affect chocolate fluid? I saw a similar empty
recipe earlier

**Comment by PssbleTrngle** [comment]
No, I don't think I did anything to chocolate
