### ISSUE TITLE
Not able to Input tools

### ISSUE THREAD

**Issue by ThickestFry** [PssbleTrngle/SliceAndDice#83]
### What happened?

No matter what kind of knife I use, I am unable to input tools into the slicer. Axes seems to work just fine though.

### Loader

forge

### Mod Version

sliceanddice-forge-2.2.0.jar

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
Sounds like a mod/datapack breaks the `forge:tools/knives` item tag, can you post the log file?

**Comment by ThickestFry** [comment]
> Sounds like a mod/datapack breaks the `forge:tools/knives` item tag, can you post the log file?

For sure but im just not sure were to look, i figured that was the issue but no idea were to find that file

**Comment by PssbleTrngle** [comment]
The log file is in the instance folder (for example the .minecraft folder, or wherever your modpack is installed) under logs/latest.log

**Comment by ThickestFry** [comment]
[2023-06-07-1.log.gz](https://github.com/PssbleTrngle/SliceAndDice/files/11827858/2023-06-07-1.log.gz)
I think this is the one, im not sure how it will help because the game runs just fine so idk

**Comment by PssbleTrngle** [comment]
Pretty sure that's not the one, there is no mention of slice-and-dice & it's from june the 7th. Just run it again with the mod enabled & upload the `latest.log` file

**Comment by ThickestFry** [comment]
[latest.log](https://github.com/PssbleTrngle/SliceAndDice/files/11843021/latest.log)
Sorry for the late response but here it is

**Comment by PssbleTrngle** [comment]
It's because of [this mod](https://www.curseforge.com/minecraft/mc-mods/farmers-compats), because they have hardcoded support for aquacultures knives, but has not set them as optional. That means the `farmersdelight:tools/knives` tag breaks if aquaculture is not installed.
They sadly have no issue tracker linked & probably also don't have a source repository, since it's a mccreator mod.

**Comment by ThickestFry** [comment]
Ight bet so i figure installing the mod will fix the issue right?

**Comment by PssbleTrngle** [comment]
Either installing aquaculture, but that's a bit of a weird solution, since you probably not want it.
You could also just remove the "farmers compats" mod which causes the issue, since it does almost nothing anyway
