### ISSUE TITLE
Compatibility for Create 0.5.1 [Fabric]

### ISSUE THREAD

**Issue by rinebergc** [PssbleTrngle/SliceAndDice#84]
### Describe the feature you have in mind.

Fabric version of S&D has not yet been updated to support Create 0.5.1.

**Comment by rinebergc** [comment]
`com.simibubi.create.content.AllSections`
has been removed in 0.5.1b.

**Comment by PssbleTrngle** [comment]
Oh nice, create fabric has been updated to 0.5.1
