### ISSUE TITLE
Crash when installed

### ISSUE THREAD

**Issue by Catomax262** [PssbleTrngle/SliceAndDice#9]
### What happened?

For some reason it crashes. Yeah, even if Create or Neapolitan are installed.

### Mod Version

1.0.2

### Forge Version

40.1.73

### Relevant log output

```shell
not a log but rather a crash report: https://mclo.gs/8QUthZg
```

**Comment by PssbleTrngle** [comment]
This does not look like it has anything to do with the mod, the log does not even mention it

**Comment by Catomax262** [comment]
But for some reason it always crashes when installing this mod. It DOES have to do with this mod. Next time analyse crash reports better. It doesn't always specify if the mod crashed or not.

**Comment by PssbleTrngle** [comment]
Can you send me a list of the mods you are using?

**Comment by Catomax262** [comment]
https://pastebin.com/vk40SJhY

**Comment by GamesJokoDylan** [comment]
is there already a solution

**Comment by PssbleTrngle** [comment]
I was not yet able to recreate this bug, I am not sure if it is an incompatibility with one of the many other mods in this log, or simply the error of another mod.

Which mods are you using and do you get the same error?

**Comment by GamesJokoDylan** [comment]
when i put the mod in the mods folder i try to start minecraft it wont start but when you take the mod out minecraft just start up sorry for bad english.

mod list
https://pastebin.com/e26edMkr

**Comment by PssbleTrngle** [comment]
Do you have the mod "Kotlin for Forge"?

**Comment by Catomax262** [comment]
Yes.

**Comment by PssbleTrngle** [comment]
I'm still pretty sure that the original crash from @Catomax262  this was opened for is not caused by this mod.
@GamesJokoDylan crash is due to him missing [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
