### ISSUE TITLE
'sliceanddice:allowed_tools' tag doesn't exist

### ISSUE THREAD

**Issue by KodYazanDruid** [PssbleTrngle/SliceAndDice#92]
### What happened?

I can't give items 'sliceanddice:allowed_tools' tag because it doesn't exist. I am using KubeJS to give items tags. I can give custom tags but not this. And i cant give Slicer to any knife idk why.

### Loader

forge

### Mod Version

sliceanddice-forge-1.2.2

### Minecraft Version

1.18

**Comment by PssbleTrngle** [comment]
Can you upload the `latest.log` file?

**Comment by KodYazanDruid** [comment]
[latest.log](https://github.com/PssbleTrngle/SliceAndDice/files/12209775/latest.log)

Prolly some createa addon messing it up.

**Comment by KodYazanDruid** [comment]
`[29Jul2023 14:35:51.220] [Worker-ResourceReload-12/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag sliceanddice:allowed_tools as it is missing following references: #forge:tools/axes (from sliceanddice-forge-1.2.3.jar)
`  hmm i think i found the problem at line 39867. Twilight Delight migh cause the problem because forge:tools/axes couldn't load because of this mod.

**Comment by KodYazanDruid** [comment]
https://github.com/Laokuai233/Twilight-Delight/issues/26 You already reported this issue 1 year ago kek.

**Comment by KodYazanDruid** [comment]
![image](https://github.com/PssbleTrngle/SliceAndDice/assets/45048634/82c66e8a-625d-49da-a70d-519811f37ec9)
I will try to solve this issue with KubeJS if i can't i will remove this twilight delight addon sadly.

**Comment by PssbleTrngle** [comment]
I've also found [this interesting mod](https://modrinth.com/mod/lmft) very recently, which should change the tag loading logic to always make entries optional, thereby a single tag file cannot break the entire tag. Should also solve your problem
