### ISSUE TITLE
Sprinkler does not exist

### ISSUE THREAD

**Issue by myrddraall** [PssbleTrngle/SliceAndDice#93]
### What happened?

Sprinkler does not exist

### Loader

forge

### Mod Version

3.0.2

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Pretty sure it's just missing from the creative tab & therefore the search, couldn't figure out why yet.
You should still be able to craft and use it tho

**Comment by spotishii** [comment]
Nah, I can't craft it or even find it with JEI. Not sure why. I'm going to look into this further.

**Comment by PssbleTrngle** [comment]
Found why it was not visible in the creative tabs/JEI and fixed it.
This should not have affected the ability to craft it tho, if that still is an issue to you please feel free to report that
